import type { Metadata } from "next";
import { Raleway, Roboto } from "next/font/google";
import "@/app/globals.css";
import ToastProvider from "@/components/common/ToastProvider";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"]
})

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${roboto.variable} antialiased flex justify-center items-center min-h-dvh`}
      >
        {children}
        <ToastProvider />
      </body>
    </html>
  );
}
